id: P003274
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18955
  title: སྙན་རྩོམ་ཐོར་བུ་ཕྱོགས་སྡེབས་མཁས་པའི་འཇུག་སྒོ།སྨད་ཆ།
  author: ''
  volumes:
    a3835217dce24152856cf347f7d30f56:
      image_group_id: I8LS18957
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
